server:
  port: 9092
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
      config:
        namespace: public
        server-addr: localhost:8848
  data:
    redis:
      database: 0
      host: localhost
      port: 6379

management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

tlog:
  pattern: $preApp-$preHost-$preIp-$spanId-$traceId

